version: '3.2'

networks:
    nodex:
      driver: overlay
      attachable: true

services:

  cli:
    hostname: cli
    image: hyperledger/fabric-tools
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=nodex_nodex
      - FABRIC_LOGGING_SPEC=DEBUG=DEBUG
      - CORE_CHAINCODE_KEEPALIVE=10
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.group:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/group/users/Admin@group/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    #command: /bin/bash -c 'sleep 1000'
    volumes:
      - /var/run/:/host/var/run/
      - ../chaincode:/opt/gopath/src/github.com/
      - ../channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
      - ../crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
    networks:
      - nodex
    depends_on:
      - orderer0.group
      - orderer1.group
      - peer0.group
      - peer1.group
      
  ca:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.group
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.group-cert.pem
      # # the below must match keyfile found in crypto-config/peerOrganizations/group/ca/
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${CA_KEYFILE}
      
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ../crypto-config/peerOrganizations/group/ca:/etc/hyperledger/fabric-ca-server-config
    hostname: ca.group
    networks:
      - nodex
