version: '3.3'

networks:
    nodex:
        driver: overlay
        attachable: true

services:
    orderer0_group:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
        image: hyperledger/fabric-orderer
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric
        command: orderer
        hostname: orderer0.group
        environment:
            - FABRIC_LOGGING_SPEC=DEBUG
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=nodex_nodex
            - ORDERER_GENERAL_LOGLEVEL=debug
            - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            - ORDERER_GENERAL_GENESISMETHOD=file
            - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
            - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
            - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp
            - ORDERER_GENERAL_TLS_ENABLED=false
            - ORDERER_GENERAL_LISTENPORT=7050
            - ORDERER_GENERAL_LEDGERTYPE=ram
            - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
            - ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
            - ORDERER_KAFKA_VERBOSE=true
            - ORDERER_ABSOLUTEMAXBYTES=10MB
            - ORDERER_PREFERREDMAXBYTES=512KB
        ports:
          - 7050:7050
        volumes:
          - ../channel-artifacts:/etc/hyperledger/configtx
          - ../crypto-config/peerOrganizations/group/peers/peer0.group:/etc/hyperledger/msp/peerOrg1
          - ../crypto-config/ordererOrganizations/group/orderers/orderer0.group/msp:/etc/hyperledger/msp
        networks:
          nodex:
            aliases:
                - orderer0.group
                
    orderer1_group:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
        image: hyperledger/fabric-orderer
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric
        command: orderer
        hostname: orderer1.group
        environment:
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=nodex_nodex
            - ORDERER_GENERAL_LOGLEVEL=debug
            - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
            - ORDERER_GENERAL_GENESISMETHOD=file
            - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
            - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
            - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp
            - ORDERER_GENERAL_TLS_ENABLED=false
            - ORDERER_GENERAL_LISTENPORT=7050
            - ORDERER_GENERAL_LEDGERTYPE=ram
            - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
            - ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
            - ORDERER_KAFKA_VERBOSE=true
            - ORDERER_ABSOLUTEMAXBYTES=10MB
            - ORDERER_PREFERREDMAXBYTES=512KB
        ports:
          - 8050:7050
        volumes:
          - ../channel-artifacts:/etc/hyperledger/configtx
          - ../crypto-config/peerOrganizations/group/peers/peer0.group:/etc/hyperledger/msp/peerOrg1
          - ../crypto-config/ordererOrganizations/group/orderers/orderer1.group/msp:/etc/hyperledger/msp
        networks:
          nodex:
            aliases:
                - orderer1.group