version: '3.2'

networks:
    nodex:
      driver: overlay
      attachable: true

services:
    peer0_group:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
        image: hyperledger/fabric-peer
        hostname: peer0.group
        environment:
            - FABRIC_LOGGING_SPEC=INFO
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=nodex_nodex
            - CORE_PEER_ADDRESSAUTODETECT=true
            - CORE_PEER_GOSSIP_ORGLEADER=false
            - CORE_PEER_GOSSIP_USELEADERELECTION=true
            - CORE_PEER_PROFILE_ENABLED=true
            - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@group/msp/
            - CORE_LOGGING_GOSSIP=WARNING
            - CORE_LOGGING_MSP=DEBUG
            - CORE_PEER_TLS_ENABLED=false
            - CORE_PEER_ID=peer0.group
            - CORE_PEER_ADDRESS=peer0.group:7051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.group:7051
            - CORE_PEER_LOCALMSPID=Org1MSP
        volumes:
            - /var/run/:/host/var/run/
            - ../crypto-config/peerOrganizations/group/peers/peer0.group/msp:/etc/hyperledger/msp/peer
            - ../crypto-config/peerOrganizations/group/users:/etc/hyperledger/msp/users 
            - ../channel-artifacts:/etc/hyperledger/configtx
        command: peer node start
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        ports:
            - 7051:7051
            - 7052:7052
            - 7053:7053
        networks:
          nodex:
            aliases:
                - peer0.group

    peer1_group:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
        image: hyperledger/fabric-peer
        hostname: peer1.group
        environment:
            - FABRIC_LOGGING_SPEC=INFO
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=nodex_nodex
            - CORE_PEER_ADDRESSAUTODETECT=true
            - CORE_PEER_GOSSIP_ORGLEADER=false
            - CORE_PEER_GOSSIP_USELEADERELECTION=true
            - CORE_PEER_PROFILE_ENABLED=true
            - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@group/msp/
            - CORE_LOGGING_GOSSIP=WARNING
            - CORE_LOGGING_MSP=DEBUG
            - CORE_PEER_ID=peer1.group
            - CORE_PEER_ADDRESS=peer1.group:7051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.group:7051
            - CORE_PEER_LOCALMSPID=Org1MSP
        volumes:
            - /var/run/:/host/var/run/
            - ../crypto-config/peerOrganizations/group/peers/peer1.group/msp:/etc/hyperledger/msp/peer
            - ../crypto-config/peerOrganizations/group/users:/etc/hyperledger/msp/users
            - ../channel-artifacts:/etc/hyperledger/configtx
        command: peer node start
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        ports:
            - 8051:7051
            - 8052:7052
            - 8053:7053
        networks:
          nodex:
            aliases:
                - peer1.group