version: '3.3'

networks:
  nodex:
      driver: overlay
      attachable: true

services:
  zookeeper0:
    image: hyperledger/fabric-zookeeper
    hostname: zookeeper0.group
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=nodex
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    # Give network alias
    networks:
      - nodex

  zookeeper1:
    image: hyperledger/fabric-zookeeper
    hostname: zookeeper1.group
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=nodex
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
      - ZOO_MY_ID=2
    # Give network alias
    networks:
      - nodex

  zookeeper2:
    image: hyperledger/fabric-zookeeper
    hostname: zookeeper2.group
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    environment:
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=nodex
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    # Give network alias
    networks:
      - nodex
